import { ElementModels, LanguageVariantResponses, SharedModels } from '../../../lib';
import * as jsonResponse from '../fake-responses/language-variants/fake-upsert-language-variant.json';
import { cmLiveClient, getTestClientWithJson, testProjectId } from '../setup';

describe('Upsert language variant', () => {
    let response: LanguageVariantResponses.UpsertLanguageVariantResponse;

    beforeAll(async () => {
        response = await getTestClientWithJson(jsonResponse)
            .upsertLanguageVariant()
            .byItemCodename('x')
            .byLanguageCodename('x')
            .withData((builder) => {
                return {
                    elements: [
                        builder.textElement({
                            element: {
                                codename: 'xElementCodename'
                            },
                            value: 'xText'
                        }),
                        builder.richTextElement({
                            element: {
                                codename: 'x'
                            },
                            value: '<p>yyy<p>',
                            components: [
                                {
                                    id: 'xzy',
                                    type: {
                                        codename: 'y'
                                    },
                                    elements: [
                                        {
                                            element: {
                                                codename: 'y'
                                            },
                                            value: 'y'
                                        }
                                    ]
                                }
                            ]
                        }),
                        builder.numberElement({
                            element: {
                                codename: 'zElementCodename'
                            },
                            value: 9
                        }),
                        builder.urlSlugElement({
                            element: {
                                codename: 'yElementCodename'
                            },
                            mode: 'autogenerated',
                            value: 'xUrlSlug'
                        }),
                        {
                            element: {
                                codename: 'personas'
                            },
                            value: [
                                {
                                    codename: 'barista'
                                },
                                {
                                    codename: 'coffee_blogger'
                                }
                            ]
                        }
                    ],
                    workflow: {
                        step_identifier: {
                            codename: 'y'
                        },
                        workflow_identifier: {
                            codename: 'x'
                        }
                    }
                };
            })
            .toPromise();
    });

    it(`url should be correct`, () => {
        const codenameUrlWithCodenameLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemCodename('xCodename')
            .byLanguageCodename('xLanguageCodename')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();
        const internalIdUrlWithCodenameLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemId('xItemId')
            .byLanguageCodename('xLanguageCodename')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();
        const externalIdUrlWithCodenameLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemExternalId('XItemExternal')
            .byLanguageCodename('xLanguageCodename')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();

        const codenameUrlWithIdLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemCodename('xCodename')
            .byLanguageId('xLanguageId')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();
        const internalIdUrlWithIdLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemId('xItemId')
            .byLanguageId('xLanguageId')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();
        const externalIdUrlWithIdLanguage = cmLiveClient
            .upsertLanguageVariant()
            .byItemExternalId('XItemExternal')
            .byLanguageId('xLanguageId')
            .withData((builder) => {
                return { elements: [] };
            })
            .getUrl();

        expect(codenameUrlWithCodenameLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/codename/xCodename/variants/codename/xLanguageCodename`
        );
        expect(internalIdUrlWithCodenameLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/xItemId/variants/codename/xLanguageCodename`
        );
        expect(externalIdUrlWithCodenameLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/external-id/XItemExternal/variants/codename/xLanguageCodename`
        );

        expect(codenameUrlWithIdLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/codename/xCodename/variants/xLanguageId`
        );
        expect(internalIdUrlWithIdLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/xItemId/variants/xLanguageId`
        );
        expect(externalIdUrlWithIdLanguage).toEqual(
            `https://manage.kontent.ai/v2/projects/${testProjectId}/items/external-id/XItemExternal/variants/xLanguageId`
        );
    });

    it(`response should be instance of UpsertLanguageVariantResponse class`, () => {
        expect(response).toEqual(jasmine.any(LanguageVariantResponses.UpsertLanguageVariantResponse));
    });

    it(`response should contain debug data`, () => {
        expect(response.debug).toBeDefined();
    });

    it(`response should contain data`, () => {
        expect(response.data).toBeDefined();
        expect(response.data.elements).toBeDefined();
        expect(response.data.item).toBeDefined();
        expect(response.data.language).toBeDefined();
        expect(response.data.lastModified).toBeDefined();
    });

    it(`item properties should be mapped`, () => {
        const variant = response.data;
        const originalItem = jsonResponse;

        if (!originalItem) {
            throw Error(`Could not find original item with id '${variant.item.id}'`);
        }

        expect(variant.item).toBeDefined();
        expect(variant.language).toBeDefined();
        expect(variant.elements).toBeDefined();
        expect(variant.lastModified).toEqual(jasmine.any(Date));
        expect(variant.workflow.workflowIdentifier).toBeDefined();
        expect(variant.workflow.stepIdentifier.id).toEqual(originalItem.workflow.step_identifier.id);
        expect(variant.item).toEqual(jasmine.any(SharedModels.ReferenceObject));
        expect(variant.language).toEqual(jasmine.any(SharedModels.ReferenceObject));

        variant.elements.forEach((element) => {
            const originalElement = originalItem.elements.find((m) => m.element.id === element.element.id);

            expect(element).toEqual(jasmine.any(ElementModels.ContentItemElement));

            if (!originalElement) {
                throw Error(`Original element with id '${element.element.id}' was not found`);
            }

            if (Array.isArray(element.value)) {
                element.value.forEach((elementReference) => {
                    expect(elementReference).toEqual(jasmine.any(SharedModels.ReferenceObject));
                });
            } else {
                expect(element.value).toEqual(originalElement.value as string | number);
            }
        });
    });
});
